"""deleted_ad field added to task model

Revision ID: 97da4732f3cc
Revises: 7a48866ca680
Create Date: 2026-06-10 10:42:36.234756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97da4732f3cc'
down_revision: Union[str, None] = '7a48866ca680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('DeletedAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'DeletedAt')
    # ### end Alembic commands ###
