"""create tables

Revision ID: ee67e87bf043
Revises: 
Create Date: 2026-06-04 13:18:52.294525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee67e87bf043'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserName', sa.String(length=250), nullable=False),
    sa.Column('Password', sa.String(), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=11), nullable=True),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('UpdatedDate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('UserName')
    )
    op.create_table('tasks',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('Title', sa.String(length=150), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('DueTime', sa.DateTime(), nullable=True),
    sa.Column('Priority', sa.SmallInteger(), nullable=True),
    sa.Column('Status', sa.SmallInteger(), nullable=True),
    sa.Column('IsDeleted', sa.Boolean(), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('UpdatedDate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('users')
    # ### end Alembic commands ###
